#!/usr/bin/env bash
set -euo pipefail

TEST_KIND="${1:-}"
TEST_NAME="${2:-}"
EXTRA_PIPELINE_ARGS=("${@:3}")

if [[ -z "${TEST_KIND}" || -z "${TEST_NAME}" ]]; then
    echo "Usage: $0 <workflow|module> <name>"
    exit 1
fi

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TEST_ROOT="${PROJECT_DIR}/test-results/${TEST_KIND}/${TEST_NAME}"
LABKEY_BASE_URL="${CI_LABKEY_BASE_URL:-https://labkey.example.org}"
LABKEY_FOLDER="${CI_LABKEY_FOLDER:-/Example/Folder}"
# Default samplesheet; workflow case overrides this before calling run_nextflow.
SAMPLESHEET="${PROJECT_DIR}/data/samplesheet.csv"

rm -rf "${TEST_ROOT}"
mkdir -p "${TEST_ROOT}"

run_nextflow() {
    local profile="${PROFILE:-test}"
    nextflow \
        -log "${TEST_ROOT}/nextflow.log" \
        run "$1" \
        -profile "${profile}" \
        -stub-run \
        -ansi-log false \
        -work-dir "${TEST_ROOT}/work" \
        -with-report "${TEST_ROOT}/report.html" \
        -with-trace "${TEST_ROOT}/trace.txt" \
        --input "${SAMPLESHEET}" \
        --outdir "${TEST_ROOT}/outputs" \
        --labkey_base_url "${LABKEY_BASE_URL}" \
        --labkey_folder "${LABKEY_FOLDER}" \
        "${@:2}"
}

case "${TEST_KIND}" in
    workflow)
        # Each workflow may need a different samplesheet format.
        case "${TEST_NAME}" in
            nmf_vae)
                # NMF-VAE needs a local-file samplesheet (sample_id,species,path,lambda_graph)
                # with >= 2 same-species samples. The real samplesheet is generated by
                # fetch_example_data.sh, which is not run in CI. Create a minimal stub
                # samplesheet inline — stub-run never reads the .rds paths, only the CSV headers.
                SAMPLESHEET="${TEST_ROOT}/nmf_vae_smoke.csv"
                mkdir -p "$(dirname "${SAMPLESHEET}")"
                cat > "${SAMPLESHEET}" <<'SAMPLESHEET_EOF'
sample_id,species,path,lambda_graph
SMOKE_A,human,/tmp/smoke_a.rds,moderate
SMOKE_B,human,/tmp/smoke_b.rds,moderate
SAMPLESHEET_EOF
                PROFILE="test_tcr_mil"
                ;;
            tcr_mil)
                # TCR MIL pipeline: QUANTIFY_TCR → TRAIN_TCR_MIL → MERGE_TCR_METADATA
                # Requires test-data/tcr/samplesheet.csv (sample,subject_id,rds)
                SAMPLESHEET="${PROJECT_DIR}/test-data/tcr/samplesheet.csv"
                PROFILE="test_tcr_mil"
                ;;
            gex_mil)
                # GEX MIL pipeline: GEX_MERGE_COUNTS → TRAIN_GEX_MIL
                # Requires test-data/gex/samplesheet.csv (sample_id,output_file_id,url,path,species,SubjectId)
                SAMPLESHEET="${PROJECT_DIR}/test-data/gex/samplesheet.csv"
                PROFILE="test_tcr_mil"
                ;;
            batch_effect_assessments)
                SAMPLESHEET="${PROJECT_DIR}/test-data/batch_effect_assessments/samplesheet.csv"
                PROFILE="test"
                ;;
            *)
                SAMPLESHEET="${PROJECT_DIR}/data/samplesheet.csv"
                PROFILE="test"
                ;;
        esac
        run_nextflow "${PROJECT_DIR}/main.nf" --workflow "${TEST_NAME}" "${EXTRA_PIPELINE_ARGS[@]}"
        case "${TEST_NAME}" in
            ingest_export)
                test -f "${TEST_ROOT}/outputs/ingest/SAMPLE_01.rds"
                test -f "${TEST_ROOT}/outputs/counts/SAMPLE_01_counts/matrix.mtx"
                ;;
            ingest_tabulate)
                test -f "${TEST_ROOT}/outputs/ingest/SAMPLE_01_metadata.csv"
                test -f "${TEST_ROOT}/outputs/tabulate/subjectIdTable.csv"
                ;;
            integration)
                test -f "${TEST_ROOT}/outputs/harmonized/harmonized_outputs/integration_manifest.csv"
                test -f "${TEST_ROOT}/outputs/scmodal/model_outputs/latent_clustered.h5ad"
                ;;
            nmf_vae)
                test -f "${TEST_ROOT}/outputs/nmf_vae/merged_counts.h5ad"
                test -f "${TEST_ROOT}/outputs/nmf_vae/genes.txt"
                test -f "${TEST_ROOT}/outputs/nmf_vae/latent_Z.csv"
                test -f "${TEST_ROOT}/outputs/nmf_vae/decoder_W.csv"
                test -f "${TEST_ROOT}/outputs/nmf_vae/loss_history.csv"
                test -f "${TEST_ROOT}/outputs/nmf_vae/loss.png"
                test -f "${TEST_ROOT}/outputs/nmf_vae/model_checkpoint.pt"
                ;;
            tcr_mil)
                # TCR MIL outputs: QUANTIFY_TCR → TRAIN_TCR_MIL → MERGE_TCR_METADATA
                test -f "${TEST_ROOT}/outputs/tcr_quant/SMOKE_01_tcr_metadata.csv"
                test -f "${TEST_ROOT}/outputs/tcr_mil/tcr_predictions.csv"
                test -f "${TEST_ROOT}/outputs/tcr_mil/tcr_model.pt"
                test -f "${TEST_ROOT}/outputs/tcr_quant/merged_tcr_metadata.csv"
                ;;
            batch_effect_assessments)
                test -f "${TEST_ROOT}/outputs/batch_effect_assessments/SMOKE_01_prep.json"
                test -f "${TEST_ROOT}/outputs/batch_effect_assessments/SMOKE_01_summary.csv"
                ;;
            make_tcr_vector_database)
                # make_tcr_vector_database outputs: per-cDNA parquet + persisted ANN index
                test -f "${TEST_ROOT}/outputs/tcr_vectordbs/vectordb_out/SAMPLE_01_single.parquet"
                test -f "${TEST_ROOT}/outputs/tcr_vectordbs/vectordb_out/SAMPLE_01_paired.parquet"
                test -f "${TEST_ROOT}/outputs/tcr_vectordbs/vectordb_out/SAMPLE_01_single_index.faiss"
                test -f "${TEST_ROOT}/outputs/tcr_vectordbs/vectordb_out/SAMPLE_01_single_index_meta.json"
                test -f "${TEST_ROOT}/outputs/tcr_vectordbs/vectordb_out/SAMPLE_01_paired_index.faiss"
                test -f "${TEST_ROOT}/outputs/tcr_vectordbs/vectordb_out/SAMPLE_01_paired_index_meta.json"
                ;;
            gex_mil)
                # GEX MIL outputs: GEX_MERGE_COUNTS → TRAIN_GEX_MIL
                test -f "${TEST_ROOT}/outputs/gex/merged_gex.h5ad"
                test -f "${TEST_ROOT}/outputs/gex_mil/predictions.csv"
                test -f "${TEST_ROOT}/outputs/gex_mil/model.pt"
                test -f "${TEST_ROOT}/outputs/gex_mil/scvi_model/model.pt"
                ;;
            *)
                echo "Unknown workflow smoke test: ${TEST_NAME}"
                exit 1
                ;;
        esac
        ;;
    module)
        run_nextflow "${PROJECT_DIR}/tests/modules/${TEST_NAME}.nf"
        case "${TEST_NAME}" in
            ingest_labkey)
                test -f "${TEST_ROOT}/outputs/ingest/TEST_SAMPLE.rds"
                ;;
            ingest_file)
                test -f "${TEST_ROOT}/outputs/ingest/TEST_SAMPLE.rds"
                test -f "${TEST_ROOT}/outputs/ingest/TEST_SAMPLE_metadata.csv"
                ;;
            ingest_metadata)
                test -f "${TEST_ROOT}/outputs/ingest/TEST_SAMPLE_metadata.csv"
                ;;
            ingest_url)
                test -f "${TEST_ROOT}/outputs/ingest/TEST_SAMPLE.rds"
                test -f "${TEST_ROOT}/outputs/ingest/TEST_SAMPLE_metadata.csv"
                ;;
            export_counts)
                test -f "${TEST_ROOT}/outputs/counts/TEST_SAMPLE_counts/matrix.mtx"
                ;;
            gene_harmonize)
                test -f "${TEST_ROOT}/outputs/harmonized/harmonized_outputs/integration_manifest.csv"
                ;;
            scmodal_integrate)
                test -f "${TEST_ROOT}/outputs/scmodal/model_outputs/latent_clustered.h5ad"
                ;;
            tabulate)
                test -f "${TEST_ROOT}/outputs/tabulate/subjectIdTable.csv"
                ;;
            *)
                echo "Unknown module smoke test: ${TEST_NAME}"
                exit 1
                ;;
        esac
        ;;
    *)
        echo "Unsupported test kind: ${TEST_KIND}"
        exit 1
        ;;
esac

echo "Smoke test completed: ${TEST_KIND}/${TEST_NAME}"
