#!/usr/bin/env Rscript

suppressWarnings(options(stringsAsFactors = FALSE))

parse_args <- function(args) {
  parsed <- list(
    output_dir = '.',
    target = 'all',
    seed = 20260414L
  )

  index <- 1L
  while (index <= length(args)) {
    key <- args[[index]]
    value <- if (index < length(args)) args[[index + 1L]] else NULL

    if (identical(key, '--output-dir') && !is.null(value)) {
      parsed$output_dir <- value
      index <- index + 2L
    } else if (identical(key, '--target') && !is.null(value)) {
      parsed$target <- value
      index <- index + 2L
    } else if (identical(key, '--seed') && !is.null(value)) {
      parsed$seed <- as.integer(value)
      index <- index + 2L
    } else if (identical(key, '--help')) {
      cat(
        paste(
          'Usage: Rscript tests/fixtures/simulate_trial_data.R',
          '--output-dir <dir>',
          '--target <metadata|counts|rds|harmonized|all>',
          '--seed <integer>\n'
        )
      )
      quit(status = 0L)
    } else {
      stop('Unknown or incomplete argument: ', key)
    }
  }

  parsed
}

write_matrix_market <- function(matrix_data, file_path) {
  indices <- which(matrix_data != 0, arr.ind = TRUE)
  lines <- c(
    '%%MatrixMarket matrix coordinate integer general',
    '% synthetic fixture generated by simulate_trial_data.R',
    sprintf('%d %d %d', nrow(matrix_data), ncol(matrix_data), nrow(indices))
  )

  if (nrow(indices) > 0) {
    entries <- sprintf(
      '%d %d %d',
      indices[, 'row'],
      indices[, 'col'],
      matrix_data[indices]
    )
    lines <- c(lines, entries)
  }

  writeLines(lines, con = file_path)
}

build_subjects <- function() {
  data.frame(
    cDNA_ID = c('SAMPLE_01', 'SAMPLE_02', 'SAMPLE_03', 'SAMPLE_04'),
    SubjectId = c('SUBJ_01', 'SUBJ_02', 'SUBJ_03', 'SUBJ_04'),
    Group = c('BCG', 'BCG', 'RhCMV', 'Control'),
    Challenge = c('Mtb', 'Mtb', 'Mtb', 'Mtb'),
    Timepoint = c('Day 7', 'Day 28', 'Day 7', 'Mock'),
    Tissue = c('Lung-R', 'Lung-L', 'BAL', 'Lung-R'),
    Vaccine = c('BCG (adult)', 'IV-BCG', 'RhCMV-TB/6Ag', 'Unvaccinated'),
    TB_Study = c('Synthetic Trial A', 'Synthetic Trial A', 'Synthetic Trial B', 'Synthetic Trial B'),
    RCaudalPathScoreLongTerm = c(1.1, 0.7, 0.5, 2.8),
    CFU_Tissue = c(2.2, 1.8, 0.6, 4.1),
    species = c('human', 'human', 'macaque', 'macaque')
  )
}

simulate_metadata <- function(seed) {
  set.seed(seed)
  subjects <- build_subjects()
  rows <- vector('list', nrow(subjects))

  for (index in seq_len(nrow(subjects))) {
    subject <- subjects[index, , drop = FALSE]
    n_cells <- 18L + index * 2L
    barcodes <- sprintf('bc%02d_%03d', index, seq_len(n_cells))

    immune_classes <- sample(
      c('TNK', 'Myeloid', 'B cell'),
      size = n_cells,
      replace = TRUE,
      prob = c(0.45, 0.4, 0.15)
    )

    tnk_class <- rep('', n_cells)
    tnk_mask <- immune_classes == 'TNK'
    tnk_class[tnk_mask] <- sample(
      c('CD4+ T Cells', 'CD8+ T Cells', 'NK'),
      size = sum(tnk_mask),
      replace = TRUE,
      prob = c(0.4, 0.4, 0.2)
    )

    myeloid_class <- rep('', n_cells)
    myeloid_mask <- immune_classes == 'Myeloid'
    myeloid_class[myeloid_mask] <- sample(
      c('Alv. mac.', 'MacrophageM1', 'Myelocytes', 'Promyelocytes', 'Neutrophils'),
      size = sum(myeloid_mask),
      replace = TRUE,
      prob = c(0.25, 0.2, 0.15, 0.15, 0.25)
    )

    tnk_type <- ifelse(
      immune_classes == 'TNK',
      sample(c('Alpha/Beta', 'Gamma/Delta'), size = n_cells, replace = TRUE, prob = c(0.75, 0.25)),
      NA_character_
    )

    activation <- round(runif(n_cells, min = 0.05, max = 0.95), 3)

    rows[[index]] <- data.frame(
      barcode = barcodes,
      cDNA_ID = subject$cDNA_ID,
      SubjectId = subject$SubjectId,
      Group = subject$Group,
      Challenge = subject$Challenge,
      Timepoint = subject$Timepoint,
      Tissue = subject$Tissue,
      RCaudalPathScoreLongTerm = subject$RCaudalPathScoreLongTerm,
      Vaccine = subject$Vaccine,
      CFU_Tissue = subject$CFU_Tissue,
      TB_Study = subject$TB_Study,
      species = subject$species,
      RIRA_Immune.cellclass = immune_classes,
      RIRA_TNK_v2.cellclass = tnk_class,
      RIRA_Myeloid_v3.cellclass = myeloid_class,
      TNK_Type = tnk_type,
      TandNK_ActivationCore_UCell = activation,
      stringsAsFactors = FALSE
    )
  }

  do.call(rbind, rows)
}

build_subject_table <- function(metadata) {
  sample_ids <- unique(metadata$cDNA_ID)
  subject_rows <- vector('list', length(sample_ids))

  for (index in seq_along(sample_ids)) {
    sample_id <- sample_ids[[index]]
    sample_df <- metadata[metadata$cDNA_ID == sample_id, , drop = FALSE]
    subject_row <- sample_df[1L, c('cDNA_ID', 'SubjectId', 'Group', 'Challenge', 'Timepoint', 'Tissue', 'RCaudalPathScoreLongTerm', 'Vaccine', 'CFU_Tissue', 'TB_Study')]

    subject_row$Total_Cells <- nrow(sample_df)
    subject_row$TNK_Fraction <- mean(sample_df$RIRA_Immune.cellclass == 'TNK')
    subject_row$Myeloid_Fraction <- mean(sample_df$RIRA_Immune.cellclass == 'Myeloid')
    subject_row$Activated_TCell_Fraction <- mean(
      sample_df$TNK_Type == 'Alpha/Beta' & sample_df$TandNK_ActivationCore_UCell >= 0.5,
      na.rm = TRUE
    )
    subject_row$Neutrophil_Fraction <- mean(sample_df$RIRA_Myeloid_v3.cellclass %in% c('Myelocytes', 'Promyelocytes', 'Neutrophils'))

    subject_rows[[index]] <- subject_row
  }

  do.call(rbind, subject_rows)
}

write_metadata_fixture <- function(output_dir, seed) {
  metadata <- simulate_metadata(seed)
  write.csv(metadata, file.path(output_dir, 'sample_metadata.csv'), row.names = FALSE)
  write.csv(build_subject_table(metadata), file.path(output_dir, 'subjectTable_TB.csv'), row.names = FALSE)
}

write_counts_fixture <- function(output_dir, seed) {
  set.seed(seed + 101L)
  counts_dir <- file.path(output_dir, 'sample_counts')
  dir.create(counts_dir, recursive = TRUE, showWarnings = FALSE)

  genes <- c('S100A8', 'S100A9', 'IL7R', 'LYZ', 'MS4A1', 'GNLY')
  barcodes <- sprintf('syn_bc_%02d', seq_len(8L))
  matrix_data <- matrix(sample(0:5, length(genes) * length(barcodes), replace = TRUE), nrow = length(genes), ncol = length(barcodes))

  obs_meta <- data.frame(
    barcode = barcodes,
    sample_id = rep('TEST_SAMPLE', length(barcodes)),
    species = rep('human', length(barcodes)),
    output_file_id = rep('100001', length(barcodes)),
    RIRA_Immune.cellclass = c('TNK', 'TNK', 'Myeloid', 'Myeloid', 'B cell', 'TNK', 'Myeloid', 'TNK'),
    stringsAsFactors = FALSE
  )

  write_matrix_market(matrix_data, file.path(counts_dir, 'matrix.mtx'))
  write.table(genes, file.path(counts_dir, 'features.tsv'), sep = '\t', quote = FALSE, row.names = FALSE, col.names = FALSE)
  write.table(barcodes, file.path(counts_dir, 'barcodes.tsv'), sep = '\t', quote = FALSE, row.names = FALSE, col.names = FALSE)
  write.csv(obs_meta, file.path(counts_dir, 'obs_meta.csv'), row.names = TRUE)
}

write_rds_fixture <- function(output_dir, seed) {
  set.seed(seed + 202L)
  payload <- list(
    synthetic = TRUE,
    seed = seed,
    sample_id = 'TEST_SAMPLE',
    note = 'Placeholder RDS fixture for smoke tests.'
  )
  saveRDS(payload, file.path(output_dir, 'sample.rds'))
}

write_harmonized_fixture <- function(output_dir, seed) {
  set.seed(seed + 303L)
  harmonized_dir <- file.path(output_dir, 'harmonized_inputs')
  dir.create(harmonized_dir, recursive = TRUE, showWarnings = FALSE)

  manifest <- data.frame(
    species = c('human', 'macaque'),
    h5ad_file = c('00_human_harmonized.h5ad', '01_macaque_harmonized.h5ad'),
    order_index = c(0L, 1L),
    stringsAsFactors = FALSE
  )

  write.csv(manifest, file.path(harmonized_dir, 'integration_manifest.csv'), row.names = FALSE)
  write.csv(data.frame(gene = c('S100A8', 'S100A9', 'IL7R', 'LYZ')), file.path(harmonized_dir, 'shared_genes.csv'), row.names = FALSE)
  write.csv(data.frame(group = c('g1', 'g1', 'g2', 'g2'), gene = c('S100A8', 'S100A9', 'IL7R', 'LYZ')), file.path(harmonized_dir, 'ortholog_mapping.csv'), row.names = FALSE)
  writeLines('4', file.path(harmonized_dir, 'n_shared.txt'))
  writeChar('synthetic h5ad placeholder', file.path(harmonized_dir, '00_human_harmonized.h5ad'), eos = NULL)
  writeChar('synthetic h5ad placeholder', file.path(harmonized_dir, '01_macaque_harmonized.h5ad'), eos = NULL)
}

args <- parse_args(commandArgs(trailingOnly = TRUE))
dir.create(args$output_dir, recursive = TRUE, showWarnings = FALSE)

targets <- if (identical(args$target, 'all')) {
  c('metadata', 'counts', 'rds', 'harmonized')
} else {
  unique(trimws(strsplit(args$target, ',', fixed = TRUE)[[1L]]))
}

for (target in targets) {
  if (identical(target, 'metadata')) {
    write_metadata_fixture(args$output_dir, args$seed)
  } else if (identical(target, 'counts')) {
    write_counts_fixture(args$output_dir, args$seed)
  } else if (identical(target, 'rds')) {
    write_rds_fixture(args$output_dir, args$seed)
  } else if (identical(target, 'harmonized')) {
    write_harmonized_fixture(args$output_dir, args$seed)
  } else {
    stop('Unsupported target: ', target)
  }
}